---
galaxy_info:
  author: "Miguel Angel Montilla Garcia"
  description: "Role para desplegar AWX sobre Docker"
  company: "Michillas"
  license: "MIT"
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 8
        - 9
