---
- name: test
  hosts: all
  become: yes
  tasks:
    - name: Create a usuario
      ansible.builtin.user:
        name: '{{ nombreusuario }}'
    - name: Agregar usuario al grupo de sudo (Administrador)
      user:
        name: '{{ nombreusuario }}'
        groups: wheel # CentOS, en Ubuntu/Debian es root
        append: yes