---
- name: test
  hosts: all
  tasks:
    - name: Listar carpetas
      find:
        path: '/home/trainer'
        file_type: "any"
      register: directorios
    - name: Debug
      debug:
        var: directorios