---
- name: "[INICIO] Despliegue AWX sobre Docker"
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: awx_docker

  post_tasks:
    - debug:
        msg: "[FIN] Despliegue AWX sobre Docker"
